/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoinIdRouteImport } from './routes/coin.$id'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinIdRoute = CoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/pay': typeof PayRoute
  '/spend': typeof SpendRoute
  '/stream': typeof StreamRoute
  '/vault': typeof VaultRoute
  '/coin/$id': typeof CoinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/pay': typeof PayRoute
  '/spend': typeof SpendRoute
  '/stream': typeof StreamRoute
  '/vault': typeof VaultRoute
  '/coin/$id': typeof CoinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/pay': typeof PayRoute
  '/spend': typeof SpendRoute
  '/stream': typeof StreamRoute
  '/vault': typeof VaultRoute
  '/coin/$id': typeof CoinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/markets'
    | '/pay'
    | '/spend'
    | '/stream'
    | '/vault'
    | '/coin/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/markets' | '/pay' | '/spend' | '/stream' | '/vault' | '/coin/$id'
  id:
    | '__root__'
    | '/'
    | '/markets'
    | '/pay'
    | '/spend'
    | '/stream'
    | '/vault'
    | '/coin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketsRoute: typeof MarketsRoute
  PayRoute: typeof PayRoute
  SpendRoute: typeof SpendRoute
  StreamRoute: typeof StreamRoute
  VaultRoute: typeof VaultRoute
  CoinIdRoute: typeof CoinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$id': {
      id: '/coin/$id'
      path: '/coin/$id'
      fullPath: '/coin/$id'
      preLoaderRoute: typeof CoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketsRoute: MarketsRoute,
  PayRoute: PayRoute,
  SpendRoute: SpendRoute,
  StreamRoute: StreamRoute,
  VaultRoute: VaultRoute,
  CoinIdRoute: CoinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
